version: "3"

services:
  terraform:
    image: hashicorp/terraform:latest
    environment:
      AWS_ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["init"]
